### ISSUE TITLE
Version 7.4.3, two Builds Failed, win_64_python3.10.____cpython & osx osx_arm64_python3.11.____cpython

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/coverage-feedstock#110]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

@thewchan @ericmjl @jakirkham @ocefpaf

A couple of the builds for 7.4.3 failed yesterday - due to intermittent issues. 

could you please rerun the feed feedstocks - https://github.com/conda-forge/coverage-feedstock/runs/21928360369

![image](https://github.com/conda-forge/coverage-feedstock/assets/95496360/2e25ee0d-bb3b-4cb0-af0f-ac524912b3fa)

### Installed packages

```shell
conda build
```

### Environment info

```shell
conda build
```

**Comment by jakirkham** [comment]
Looks like this was already addressed: https://github.com/conda-forge/coverage-feedstock/pull/111

Can see a green checkmark on the latest commit

Closing as resolved
